// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeaccqdlbvpjojqkfdlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlYWNjcWRsYnZwam9qcWtmZGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Mzc2MzgsImV4cCI6MjA2ODQxMzYzOH0.oMbNBB1sIWmeGZ18L4P6lNYmMazEwKSeXUJYCQaf1-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});